#!/usr/bin/env bun
/**
 * Build a self-contained native executable.
 *
 * Usage:
 *   bun run scripts/build-exe.ts
 *   OUTFILE=dist/claude-cockpit-linux-x64 bun run scripts/build-exe.ts
 *   SKIP_VITE_BUILD=1 bun run scripts/build-exe.ts   # reuse existing dist/client
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from 'fs'
import { join, relative, extname } from 'path'
import { execSync } from 'child_process'

const root = join(import.meta.dirname, '..')
const distDir = join(root, 'dist', 'client')
const embeddedClientPath = join(root, 'src', 'server', 'embedded-client.ts')

const MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js':   'application/javascript',
  '.css':  'text/css',
  '.svg':  'image/svg+xml',
  '.ico':  'image/x-icon',
  '.png':  'image/png',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.json': 'application/json',
}

// ── 1. Build Vite frontend ──────────────────────────────────────────────────

if (!process.env.SKIP_VITE_BUILD) {
  console.log('[build-exe] Building frontend...')
  execSync('npx vite build', { stdio: 'inherit', cwd: root })
} else {
  console.log('[build-exe] Skipping Vite build (SKIP_VITE_BUILD=1)')
}

// ── 2. Walk dist/client and base64-encode every asset ──────────────────────

function walk(dir: string): string[] {
  const files: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) files.push(...walk(full))
    else files.push(full)
  }
  return files
}

const files = walk(distDir)
const entries = files.map((file) => {
  const urlPath = '/' + relative(distDir, file).replace(/\\/g, '/')
  const mime    = MIME[extname(file)] ?? 'application/octet-stream'
  const content = readFileSync(file).toString('base64')
  return `  ${JSON.stringify(urlPath)}: { content: ${JSON.stringify(content)}, mime: ${JSON.stringify(mime)} }`
})

writeFileSync(
  embeddedClientPath,
  `// Auto-generated by scripts/build-exe.ts — do not edit manually\n` +
  `export const embeddedClient: Record<string, { content: string; mime: string }> = {\n` +
  entries.join(',\n') + '\n}\n',
)
console.log(`[build-exe] Embedded ${files.length} assets into embedded-client.ts`)

// ── 3. Compile with Bun ────────────────────────────────────────────────────

const defaultOut = process.platform === 'win32'
  ? 'dist/claude-cockpit.exe'
  : 'dist/claude-cockpit'
const outfile = process.env.OUTFILE ?? defaultOut

console.log(`[build-exe] Compiling → ${outfile}`)
execSync(
  `bun build --compile src/server/index.ts --outfile ${outfile}`,
  { stdio: 'inherit', cwd: root },
)
console.log(`[build-exe] Done! Binary: ${outfile}`)

// ── 4. Reset embedded-client.ts to empty placeholder ──────────────────────
//    So the committed file stays clean (not a multi-MB blob in git)

writeFileSync(
  embeddedClientPath,
  `// Auto-generated by scripts/build-exe.ts — do not edit manually\n` +
  `export const embeddedClient: Record<string, { content: string; mime: string }> = {}\n`,
)
console.log('[build-exe] Reset embedded-client.ts to empty placeholder')
